dataset :
  root_dir : '/Users/eliap/Projects/tiny_dataset'
  heuristic : 'lkh_col1_area2_pos0_cl10_sal0'
  resize : 512
  context_length : 3
  sequence_length : 5
model:
  img_encoder: 'resnet18'
  n_strokes_params : 12
  encoder:
    d_model : 0
    n_heads : 4
    n_layers : 4
  vae_encoder:
    d_model : 0
    n_heads : 4
    n_layers : 3
  vae_decoder:
    d_model : 0
    n_heads : 4
    n_layers : 3