img_path: ''
output_dir: ''
renderer: 'oilpaintbrush'
canvas_color: 'black'
canvas_size: 256
keep_aspect_ratio: False
beta_L1: 1.0
with_ot_loss: False
beta_ot: 0.1
dataset_feat_mean : '/home/eperuzzo/dataset_statistics/features_seq_ctx_mean.pth'
dataset_feat_var : '/home/eperuzzo/dataset_statistics/features_seq_ctx_var.pth'
with_kl_loss : False
beta_kl : 2.5e-6
kl_lr : 0.00005
n_iters_per_strokes : 15
net_G: 'zou-fusion-net'
renderer_checkpoint_dir: '/home/eperuzzo/checkpoints_G_oilpaintbrush'
lr: 0.005
disable_preview: True
gpu_id: 0
clamp_schedule:
  1 : 0.9
  2 : 0.9
  3 : 0.9
  4 : 0.9
  5 : 0.9
manual_storkes_params:
  1 : 9
  2 : 9
  3 : 9
  4 : 9
  5 : 9
brush_paths:
  small_vertical :  '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_small_vertical.png'
  small_horizontal : '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_small_horizontal.png'
  large_vertical : '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_vertical.png'
  large_horizontal : '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_horizontal.png'