dataset :
  root_dir : '/Users/eliap/Projects/tiny_dataset'
  heuristic : 'lkh_col1_area2_pos0_cl10_sal0'
  resize : 256
  context_length : 4
  sequence_length : 8
model:
  d_model : 256
  img_encoder: 'resnet18'
  n_strokes_params : 12
  merge_type : 'sum'
  encoder:
    n_heads : 8
    n_layers : 3
  vae_encoder:
    n_heads : 8
    n_layers : 3
  vae_decoder:
    n_heads : 8
    n_layers : 3
train:
  n_epochs : 50
  gpu_id : 0
  batch_size : 1
  checkpoint_path : '/home/eperuzzo/brushstrokes/ckpt/'
  lr :  0.0005
  wd : 0.000001
  save_freq : 20