dataset :
  root : '/home/eperuzzo/IBG_dataset/'
  csv_file : '/home/eperuzzo/IBG_dataset/dataset_test_config.csv'
  partition : 'oxford_pet_dataset'
  heuristic : 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 10
  sequence_length : 8
  use_images : True
  sampling:
    active : False
    threshold: 0
    prob: 0
renderer:
  brushes_path:
    large_vertical: '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_vertical.png'
    large_horizontal: '/home/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_horizontal.png'
  painter_config : '/home/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config_sibiu.yaml'
  freq : 1
gpu_id : 0