dataset :
  root : '/home/eperuzzo/IBG_dataset/'
  csv_file : '/home/eperuzzo/IBG_dataset/dataset_test_config.csv'
  partition : ade_dataset
  version : v2
  heuristic : lkh_col1_area1_pos0.5_cl2_sal0
  resize : 256
  context_length : 10
  sequence_length : 8
renderer:
  painter_config : '/home/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config.yaml'
  freq : 1
gpu_id : 0