dataset :
  root: '/home/eperuzzo/IBG_dataset'
  csv_file: '/home/eperuzzo/IBG_dataset/ade_test.csv'
  partition: 'ade_dataset'
  heuristic: 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 20
  context_length_old : 4
  sequence_length : 8
  use_images : True
model:
  model_type : 'full'
  name: None
  checkpoint: ''
  d_model : 256
  n_strokes_params : 12
  ctx_z : 'cat'
  activation_last_layer : 'sigmoid'
  encoder_pe: 'sine'
  decoder_pe : 'learnable'
  img_encoder:
    type : 'resnet18'
    pretrained : True
    layers_to_remove : ['fc']
  encoder:
    canvas_strokes : 'add'
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_encoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_decoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
train:
  n_epochs : 250
  gpu_id : 1
  batch_size : 256
  num_workers : 8
  seed : 43
  amp_enabled : True
  optimizer:
    max_lr : 1.0e-3
    min_lr : 1.0e-4
    warmup_lr : 1.0e-5
    warmup_ep : 50
    wd : 0.05
    clip_grad : 4.0
  kl:
    warmup_type : 'cosine'
    warm_up_epochs : 100
    kl_lambda : 2.5e-4
  auto_resume:
    active : False
    resume_path : ''
  logging:
    checkpoint_path : '/home/eperuzzo/brushstrokes/checkpoints/'
    save_freq : 25
    print_freq : 10
render:
  painter_config : '/home/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config_sibiu.yaml'
  freq : 1