dataset :
  root : '/data/eperuzzo/IBG_dataset/'
  csv_file : '/data/eperuzzo/IBG_dataset/dataset_config.csv'
  partition : 'oxford_pet_dataset'
  heuristic : 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 10
  sequence_length : 8
  use_images : True
  sampling:
    active : True
    threshold: 150
    prob: 0.35
model:
  model_type : '2_steps'
  d_model : 384
  n_strokes_params : 11
  ctx_z : 'cat'
  activation_last_layer : 'sigmoid'
  encoder_pe: 'new'
  decoder_pe : 'sine'
  img_encoder:
    type : 'resnet18'
    pretrained : True
    layers_to_remove : ['fc', 'layer4']
    visual_features_dim : 8
  encoder:
    canvas_strokes : 'add'
    act : 'gelu'
    n_heads : 6
    n_layers : 8
    ff_dim : 1536
  vae_encoder:
    act : 'gelu'
    n_heads : 6
    n_layers : 8
    ff_dim : 1536
  vae_decoder:
    act : 'gelu'
    n_heads : 6
    n_layers : 8
    ff_dim : 1536
train:
  n_epochs : 250
  gpu_id : 0
  batch_size : 256
  num_workers : 8
  seed : 43
  amp_enabled : True
  optimizer:
    max_lr : 1.0e-3
    min_lr : 1.0e-4
    warmup_lr : 1.0e-5
    warmup_ep : 50
    wd : 0.05
    clip_grad : 4.0
  kl:
    warmup_type : 'cosine'
    warm_up_epochs : 125
    kl_lambda : 2.5e-4
  auto_resume:
    active : False
    resume_path : ''
  logging:
    wandb_api_key : "5745461314f5f4abb2c957bb991d2df97144ba06"
    checkpoint_path : '/data/eperuzzo/model_checkpoints/'
    save_freq : 1000
    print_freq : 10
render:
  painter_config : '/data/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config.yaml'
  freq : 1
