dataset :
  train :
    root_dir : '/Users/eliap/Projects/tiny_dataset'
  test :
    root_dir : '/Users/eliap/Projects/tiny_dataset'
  heuristic : 'lkh_col1_area2_pos0_cl10_sal0'
  partition : 'ade_dataset'
  resize : 256
  context_length : 4
  sequence_length : 8
model:
  only_vae : False
  d_model : 256
  n_strokes_params : 12
  ctx_z : 'cat'
  activation_last_layer : 'sigmoid'
  img_encoder:
    type : 'resnet18'
    pretrained : True
  encoder:
    canvas_strokes : 'add'
    context_pooling : False
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_encoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_decoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
train:
  n_epochs : 100
  gpu_id : -1
  batch_size : 64
  num_workers : 8
  amp_enabled : False
  optimizer:
    max_lr : 7.0e-4
    min_lr : 5.0e-5
    warmup_lr : 5.0e-6
    warmup_ep : 20
    wd : 0.05
    clip_grad : 4.0
  kl:
    warmup_type : 'linear'
    warm_up_epochs : 10
    kl_lambda : 5.0e-5
  auto_resume:
    active : False
    resume_path : ''
  logging:
    checkpoint_path : '/data/eperuzzo/brushstrokes-generation/checkpoints/'
    save_freq : 25
    print_freq : 10
render:
  painter_config : '/data/eperuzzo/brushstrokes-generation/code/configs/decomposition/painter_config.yaml'
  freq : 1