dataset :
  root : '/data/eperuzzo/IBG_dataset/'
  csv_file : '/data/eperuzzo/IBG_dataset/dataset_config.csv'
  partition : 'oxford_pet_dataset'
  heuristic : 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 10
  sequence_length : 8
  use_images : True
  sampling:
    active : False
    threshold: 0
    prob: 0
model:
  model_type : 'full'
  d_model : 256
  n_strokes_params : 11
  ctx_z : 'cat'
  activation_last_layer : 'identity'
  encoder_pe: 'old'
  decoder_pe : 'sine'
  img_encoder:
    type : 'convenc'
    pretrained : True
    layers_to_remove : ['fc', 'layer4']
    visual_feat_hw : 8
    visual_feat_dim : 256
    hres_feat_hw : 64
    hres_feat_dim : 64
  encoder:
    canvas_strokes : 'add'
    act : 'gelu'
    n_heads : 4
    n_layers : 8
    ff_dim : 1024
  vae_encoder:
    act : 'gelu'
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
  vae_decoder:
    act : 'gelu'
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
train:
  n_epochs : 500
  gpu_id : 0
  batch_size : 32
  num_workers : 8
  seed : 1432
  amp_enabled : False
  optimizer:
    max_lr : 1.0e-4
    min_lr : 1.0e-4
    warmup_lr : 1.0e-6
    warmup_ep : 20
    wd : 1.0e-6
    clip_grad : 10.0
  kl:
    warmup_type : 'cosine'
    warm_up_epochs : 50
    kl_lambda : 1.0e-4
  loss_weights :
    position : 1
    size : 1
    theta : 1
    color : 1
    color_img : 1
  auto_resume:
    active : False
    resume_path : ''
  logging:
    wandb_api_key : "5745461314f5f4abb2c957bb991d2df97144ba06"
    checkpoint_path : '/data/eperuzzo/ablation/'
    save_freq : 100
    print_freq : 10
render:
  painter_config : '/data/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config.yaml'
  freq : 1