dataset :
  train :
    root_dir : '/home/eperuzzo/brushstrokes/ade-gen-brush-debug/train/'
  test :
    root_dir : '/home/eperuzzo/brushstrokes/ade-gen-brush-debug/test/'
  heuristic : 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 4
  sequence_length : 8
model:
  only_vae : False
  d_model : 256
  n_strokes_params : 12
  ctx_z : 'cat'
  activation_last_layer : 'sigmoid'
  img_encoder:
    type : 'resnet18'
    pretrained : True
  encoder:
    context_pooling : False
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_encoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_decoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
train:
  n_epochs : 100
  gpu_id : 1
  batch_size : 64
  num_workers : 8
  optimizer:
    max_lr : 7.0e-4
    min_lr : 5.0e-5
    warmup_lr : 5.0e-6
    warmup_ep : 20
    wd : 0.05
    clip_grad : 4.0
  kl:
    warmup_type : 'linear'
    warm_up_epochs : 10
    kl_lambda : 5.0e-5
  auto_resume:
    active : False
    resume_path : ''
  logging:
    checkpoint_path : '/home/eperuzzo/brushstrokes/checkpoints/'
    save_freq : 25
    print_freq : 10
render:
  painter_config : '/home/eperuzzo/brushstrokes/configs/decomposition/painter_config_sibiu.yaml'
  freq : 1