dataset :
  root : '/data/eperuzzo/IBG_dataset/'
  csv_file : '/data/eperuzzo/IBG_dataset/dataset_config.csv'
  partition : 'ade_dataset'
  heuristic : 'lkh_col2_area1_pos0_cl7'
  resize : 256
  context_length : 4
  sequence_length : 8
  use_images : True
model:
  model_type : 'autoencoder'
  d_model : 256
  n_strokes_params : 12
  ctx_z : 'cat'
  activation_last_layer : 'sigmoid'
  pe: 'sine'
  img_encoder:
    type : 'resnet18'
    pretrained : True
    layers_to_remove : ['fc', 'layer4']
  encoder:
    canvas_strokes : 'add'
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_encoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
  vae_decoder:
    act : 'gelu'
    n_heads : 8
    n_layers : 5
    ff_dim : 1024
train:
  n_epochs : 100
  gpu_id : 0
  batch_size : 64
  num_workers : 8
  seed : 43
  amp_enabled : True
  optimizer:
    max_lr : 5.0e-4
    min_lr : 5.0e-5
    warmup_lr : 5.0e-6
    warmup_ep : 20
    wd : 0.05
    clip_grad : 4.0
  kl:
    warmup_type : 'linear'
    warm_up_epochs : 35
    kl_lambda : 1.0e-4
  auto_resume:
    active : False
    resume_path : ''
  logging:
    wandb_api_key : "5745461314f5f4abb2c957bb991d2df97144ba06"
    checkpoint_path : '/data/eperuzzo/model_checkpoints/'
    save_freq : 1000
    print_freq : 10
render:
  painter_config : '/data/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config.yaml'
  freq : 1
