dataset :
  root :
  csv_file :
  partition : oxford_pet_dataset
  version : v2
  heuristic : lkh_col1_area1_pos0.5_cl2_sal0
  resize : 256
  context_length : 10
  sequence_length : 8
  use_images : True
  sampling:
    active : False
    threshold: 0
    prob: 0
model:
  model_type : vae
  d_model : 256
  n_strokes_params : 8
  ctx_z : cat
  activation_last_layer : sigmoid
  encoder_pe: new
  decoder_pe : sine
  dropout : 0.0
  img_encoder:
    type : convenc
    visual_feat_hw : 16
    visual_feat_dim : 256
    hres_feat_hw : 64
    hres_feat_dim : 64
  context_encoder:
    use_context: True
    use_transformer: True
    canvas_strokes : add
    act : gelu
    n_heads : 4
    n_layers : 8
    ff_dim : 1024
  encoder:
    encoder_only : False
    act : gelu
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
  decoder:
    type: 2_step
    residual_pos : False
    act : gelu
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
  discriminator:
    type : None
    num_layers : 0
    encoder_only : False
    scale_lr : 0.0
train:
  n_epochs : 5000
  gpu_id : 0
  batch_size : 32
  num_workers : 4
  seed : 1432
  amp_enabled : False
  optimizer:
    max_lr : 1.0e-4
    min_lr : 1.0e-6
    warmup_lr : 1.0e-6
    warmup_ep : 20
    wd : 0.0
    beta_1 : 0.99
    beta_2 : 0.999
    clip_grad : 10
  losses:
    gan:
      mode: None
      weight:
        G : 0.0
        D : 0.0
    kl:
      weight: 2.5e-4
      warmup_epochs : 100
      patience_epochs : 0
    reconstruction:
      mode: l2
      weight:
        position : 2.0
        size : 1.0
        theta : 1.0
        color : 0.25
    reference_img:
      render :
        mode : l2
        weight : 0.0
        type : full
      color :
        mode : l2
        weight : 0.25
        detach : False
      color_wo_z:
        mode: l2
        weight: 0.025
        detach: False
      pos_color:
        mode : l2
        find_target : knn
        weight : 0.0
        K : 0
        p : 0
        tau : 0
    fid:
      mode: kl
      weight : 5.0e-6
      K : 10
      use_context : True
      use_color : False
      reweight_kl : True
      mu_dataset :
      sigma_dataset :
  logging:
    wandb_api_key :
    project_name :
    exp_name :
    checkpoint_path :
    save_freq : 100
    print_freq : 10
    eval_every : 5
  auto_resume:
    active : False
    resume_path :
renderer:
  brushes_path:
    large_vertical:
    large_horizontal:
  painter_config :
  freq : 1