dataset :
  root : /data/eperuzzo/IBG_dataset/
  csv_file : /data/eperuzzo/IBG_dataset/dataset_config.csv
  partition : oxford_pet_dataset
  heuristic : lkh_col2_area1_pos0_cl7
  resize : 256
  context_length : 10
  sequence_length : 8
  use_images : True
  sampling:
    active : False
    threshold: 0
    prob: 0
model:
  model_type : vae-gan   # [vae, vae-gan, gan]
  d_model : 256
  n_strokes_params : 8
  ctx_z : cat
  activation_last_layer : identity
  encoder_pe: old
  decoder_pe : sine
  dropout : 0.0
  img_encoder:
    type : convenc
    visual_feat_hw : 16
    visual_feat_dim : 256
    hres_feat_hw : 64
    hres_feat_dim : 64
  context_encoder:
    canvas_strokes : add
    act : relu
    n_heads : 4
    n_layers : 8
    ff_dim : 1024
  encoder:
    act : relu
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
  decoder:
    type: 2_step
    act : relu
    n_heads : 4
    n_layers : 6
    ff_dim : 1024
  discriminator:
    type : conv1d
    num_layers : 2
    encoder_only : False
    scale_lr : 1.0
train:
  n_epochs : 500
  gpu_id : 0
  batch_size : 32
  num_workers : 4
  seed : 1432
  amp_enabled : False
  optimizer:
    max_lr : 1.0e-4
    min_lr : 1.0e-4
    warmup_lr : 1.0e-6
    warmup_ep : 20
    wd : 0.0
    beta_1 : 0.99
    beta_2 : 0.999
    clip_grad : 10
  losses:
    gan:
      mode: vanilla
      weight:
        G : 1.0
        D : 0.5
    kl:
      weight: 2.5e-3
      warmup_epochs : 100
      patience_epochs : 0
    reconstruction:
      mode: l2
      weight:
        position : 1.0
        size : 1.0
        theta : 1.0
        color : 1.0
    reference_img:
      render :
        mode : l1
        weight : 0.0
        type : full
      color :
        mode : l2
        weight : 0.25
      pos_color:
        mode : l2
        weight : 0.0
  logging:
    wandb_api_key : 5745461314f5f4abb2c957bb991d2df97144ba06
    checkpoint_path : /data/eperuzzo/IBG_checkpoints/
    save_freq : 200
    print_freq : 10
    eval_every : 1
renderer:
  brushes_path:
    large_vertical: /data/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_vertical.png
    large_horizontal: /data/eperuzzo/brushstrokes-generation/dataset_acquisition/decomposition/brushes/brush_fromweb2_large_horizontal.png
  painter_config : /data/eperuzzo/brushstrokes-generation/configs/decomposition/painter_config.yaml
  freq : 1